apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  GITHUB_OWNER: "axldev99"
  GITHUB_REPO: "etsmtl-log680-oxygencs-eq7"
  DB_NAME: "db02eq7"
  DB_USER: "user02eq7"
  DB_HOST: "157.230.69.113"
  DB_PASS: "EKvaUWzO0mHHdXuD"
  KANBAN_COLUMN: "value1;value2;value3"
  OWNER: "axldev99"
  REPO: "etsmtl-log680-oxygencs-eq7"
  HOST: "http://159.203.50.162/"
  T_MIN: "18"
  T_MAX: "25"
  TICKS: "5"
